apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: app
      service: myapp1
  template:
    metadata:
      labels:
        type: app
        service: myapp1
    spec:
      containers:
        - name: myapp1
          image: hothoony/k8s-test:v2
          - ports:
          containerPort: 8080
