apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test
      tier: backend
    template:
      metadata:
        labels:
          app: k8s-test
          tier: backend
      spec:
        containers:
          - name: k8s-test
            image: hothoony/k8s-test:{TAG}